language: node_js
node_js:
    - "stable"
cache:
    directories:
        - "node_modules"
script:
    - npm start -- --silent &
    - npm run cy:run
    # after all tests finish running we need
    # to kill all background jobs (like "npm start &")
    - kill $(jobs -p) || true
