language: node_js
node_js:
    - "stable"
cache:
    directories:
        - "node_modules"
script:
    - npm start -- --silent &
    - npm run cy:run
    - npm run test
    # after all tests finish running we need
    # to kill all background jobs (like "npm start &")
    - kill $(jobs -p) || true

notifications:
    webhooks:
        urls:
            - https://webhook.atomist.com/atomist/travis/teams/AKQMMNPJR
        on_success: always
        on_failure: always
        on_start: always
        on_cancel: always
        on_error: always
